export const navigations = [
  {
    _id: "1",
    name: "Dashboard",
    icon: "ti ti-layout",
    parent_id: "",
    route: "/dashboard",
    is_header: 0,
    is_active: 1,
    order: 1,
    roles: [
      "super_admin",
      "admin",
      "user"
    ],
    permissions: [],
    description: "Dashboard main page for users",
    level: 0,
    component: "Dashboard",
    is_visible: 1,
  },
  {
    _id: "2",
    name: "Data Hero",
    icon: "ti ti-database",
    parent_id: "",
    route: "",
    is_header: 1,
    is_active: 1,
    order: 2,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data hero header menu page for users",
    level: 0,
    component: "DataHero",
    is_visible: 1,
  },
  {
    _id: "3",
    name: "Data Hero",
    icon: "",
    parent_id: "2",
    route: "/data-hero/hero",
    is_header: 0,
    is_active: 1,
    order: 1,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data hero main page for users",
    level: 1,
    component: "DataHero",
    is_visible: 1,
  },
  {
    _id: "4",
    name: "Data Skill",
    icon: "",
    parent_id: "2",
    route: "/data-hero/skill",
    is_header: 0,
    is_active: 1,
    order: 2,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data skill main page for users",
    level: 1,
    component: "DataSkill",
    is_visible: 1,
  },
  {
    _id: "5",
    name: "Data Base Stat",
    icon: "",
    parent_id: "2",
    route: "/data-hero/base-stat",
    is_header: 0,
    is_active: 1,
    order: 3,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data base stat main page for users",
    level: 1,
    component: "DataBaseStat",
    is_visible: 1,
  },
  {
    _id: "6",
    name: "Data Persiapan",
    icon: "ti ti-file-pencil",
    parent_id: "",
    route: "",
    is_header: 1,
    is_active: 1,
    order: 3,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data persiapan main page for users",
    level: 0,
    component: "DataPersiapan",
    is_visible: 1,
  },
  {
    _id: "7",
    name: "Data Emblem",
    icon: "",
    parent_id: "6",
    route: "/data-persiapan/emblem",
    is_header: 0,
    is_active: 1,
    order: 1,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data emblem main page for users",
    level: 1,
    component: "DataEmblem",
    is_visible: 1,
  },
  {
    _id: "8",
    name: "Data Item",
    icon: "",
    parent_id: "6",
    route: "/data-persiapan/item",
    is_header: 0,
    is_active: 1,
    order: 2,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data item main page for users",
    level: 1,
    component: "DataItem",
    is_visible: 1,
  },
  {
    _id: "9",
    name: "Data Battle Spell",
    icon: "",
    parent_id: "6",
    route: "/data-persiapan/battle-spell",
    is_header: 0,
    is_active: 1,
    order: 3,
    roles: [
      "super_admin",
      "admin"
    ],
    permissions: [],
    description: "Data battle spell main page for users",
    level: 1,
    component: "DataBattleSpell",
    is_visible: 1,
  }
]